server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

mail:
  to: danilvda@gmail.com

dir:
  data: src/main/resources/data

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: SPRING_SESSION
  mail:
    host: smtp.yandex.ru
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtps

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
